Models/Folder.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DMS.Models
{
    public class Folder : Item
    {
        public int Id { get; set; }

        public bool IsComposite()
        {
            return true;
        }

        public string? Name { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateModified { get; set; }

        public List<Item> Contents = new List<Item>();

        public Department Department { get; set; }

        public Faculty Faculty { get; set; }

        public int ParentId { get; set; }
    }
}

Controllers/FoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using System.Dynamic;
using DMS.Models;
using DMS.Data;
using DMS.Helpers;
using System.Text.Json;

namespace DMS.Controllers
{
    public class FoldersController : BaseController
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly DemoDMSContext _context;
        private readonly UserInfo _userInfo;

        public FoldersController(DemoDMSContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            var userJson = _httpContextAccessor.HttpContext.Session.GetString("UserInfo");
            if (userJson != null)
            {
                if (!string.IsNullOrEmpty(userJson))
                {
                    var userInfo = JsonSerializer.Deserialize<UserInfo>(userJson);
                    _userInfo = userInfo;
                }
            }

        }

        // GET: Folders
        [RoleAccessFilter("ConfigA")]
        public async Task<IActionResult> Index(int id, string searchString)
        {
            ViewBag.currentID = id;
            if(_userInfo == null) return RedirectToAction("Index", "Home");

            Enum.TryParse<Faculty>(_userInfo.Division, out var divisionEnum);
            Enum.TryParse<Department>(_userInfo.Department, out var departmentEnum);

            var folders = from m in _context.Folder where m.Faculty == divisionEnum && m.Department == departmentEnum select m;
            var documents = from m in _context.Document where m.Faculty == divisionEnum && m.Department == departmentEnum select m; 

            dynamic model = new ExpandoObject();

            if (!string.IsNullOrEmpty(searchString))
            {
                model.Folders = folders.Where(m => m.Name.ToLower()!.Contains(searchString.ToLower()));
                model.Documents = documents.Where(m => m.Name.ToLower()!.Contains(searchString.ToLower()));
            }
            else
            {
                model.Folders = folders.Where(m => m.ParentId == id);
                model.Documents = documents.Where(m => m.ParentId == id);
            }

            if (id == 0)
            {
                ViewBag.parentId = 0;
            }
            else
            {
                var folder = await _context.Folder.FirstOrDefaultAsync(m => m.Id == id);
                ViewBag.parentId = folder.ParentId;
            }

            return View(model);
        }

        // GET: Folders/Create
        [RoleAccessFilter("ConfigB")]
        public IActionResult Create(int id)
        {
            ViewBag.parentId = id;

            return View();
        }

        // POST: Folders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleAccessFilter("ConfigB")]
        public async Task<IActionResult> Create(string name, Faculty faculty, Department department, int parentId)
        {
            Folder folder = new Folder
            {
                Name = name,
                DateCreated = DateTime.Now,
                DateModified = DateTime.Now,
                ParentId = parentId,
                Faculty = faculty,
                Department = department
            };

            var parentFolder = await _context.Folder.FindAsync(parentId);

            if (parentFolder != null)
            {
                parentFolder.Contents.Add(folder);
            }

            _context.Add(folder);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = parentId });
        }

        // GET: Folders/Edit/5
        [RoleAccessFilter("ConfigB")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Folder == null)
            {
                return NotFound();
            }

            var folder = await _context.Folder.FindAsync(id);

            if (folder == null)
            {
                return NotFound();
            }

            ViewBag.parentId = folder.ParentId;

            return View(folder);
        }

        // POST: Folders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleAccessFilter("ConfigB")]
        public async Task<IActionResult> Edit(int id, string name, Faculty faculty, Department department, int parentId)
        {
            if (id == null || _context.Folder == null)
            {
                return NotFound();
            }

            var folder = await _context.Folder.FindAsync(id);

            if (folder == null)
            {
                return NotFound();
            }

            if (id != folder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    folder.Name = name;
                    folder.Faculty = faculty;
                    folder.Department = department;
                    folder.DateModified = DateTime.Now;
                    _context.Update(folder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FolderExists(folder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index", new { id = parentId });
            }

            return View(folder);
        }

        // GET: Folders/Delete/5
        [RoleAccessFilter("ConfigC")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Folder == null)
            {
                return NotFound();
            }

            var folder = await _context.Folder.FirstOrDefaultAsync(m => m.Id == id);

            if (folder == null)
            {
                return NotFound();
            }

            ViewBag.parentId = folder.ParentId;

            return View(folder);
        }

        // POST: Folders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RoleAccessFilter("ConfigC")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Folder == null)
            {
                return Problem("Entity set 'DemoDMScnt.Folder' is null.");
            }

            var folder = await _context.Folder.FindAsync(id);
            var parentId = folder.ParentId;

            if (folder != null)
            {
                _context.Folder.Remove(folder);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = parentId });
        }

        private bool FolderExists(int id)
        {
            return (_context.Folder?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Folders/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using DMS.Models;
@inject IViewLocalizer Localizer;

@model DMS.Models.Folder

@{
    ViewBag.title = Localizer["Create"];
}

<h4>@Localizer["Create"] -> @Localizer["Folder"]</h4>

<div class="rounded-10 p-2 div-br-color">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-parentId="@ViewBag.parentId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">@Localizer["Name"]</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Faculty" class="control-label">@Localizer["Faculty"]</label>
                    <select asp-for="Faculty" asp-items="@Html.GetEnumSelectList<Faculty>()" class="form-control"></select>
                    <span asp-validation-for="Faculty" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Department" class="control-label">@Localizer["Department"]</label>
                    <select asp-for="Department" asp-items="@Html.GetEnumSelectList<Department>()" class="form-control"></select>
                    <span asp-validation-for="Department" class="text-danger"></span>
                </div>

            <div class="form-group">
                <a asp-action="Index" asp-route-id="@ViewBag.parentId">
                    <button type="button" class="btn btn-secondary">@Localizer["Return"]</button></a>
                <input type="submit" value="@Localizer["Create"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</div>

Views/Folders/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using DMS.Models;
@inject IViewLocalizer Localizer;

@model DMS.Models.Folder

@{
    ViewBag.title = Localizer["FoldDelete"];
}

<h4>@Localizer["Folder"] -> @Localizer["FoldDelete"]</h4>
<div class="rounded-10 p-2 div-br-color">
    <br>

    <h5 class="text-danger">@Localizer["Are you sure you want to delete this?"]</h5>

<hr />

<div>

    <dl class="row">
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.Name)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <a asp-action="Index" asp-route-id="@ViewBag.parentId"><button type="button" class="btn btn-secondary">@Localizer["Return"]</button></a>
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
    </form>
</div>

</div>

Views/Folders/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using DMS.Models;
@inject IViewLocalizer Localizer;

@model DMS.Models.Folder

@{
    ViewBag.title = Localizer["FoldEdit"];
}

<h4>@Localizer["Folder"] -> @Localizer["FoldEdit"]</h4>

<div class="rounded-10 p-2 div-br-color">
    <br>

<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="Folders" asp-action="Edit" asp-route-parentId="@ViewBag.parentId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label for="Name" class="control-label">@Localizer["Name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

                <div class="form-group">
                    <label for="Department" class="control-label">@Localizer["Department"]</label>
                    <select asp-for="Department" asp-items="@Html.GetEnumSelectList<Department>()" class="form-control"></select>
                    <span asp-validation-for="Department" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Faculty" class="control-label">@Localizer["Faculty"]</label>
                    <select asp-for="Faculty" asp-items="@Html.GetEnumSelectList<Faculty>()" class="form-control"></select>
                    <span asp-validation-for="Faculty" class="text-danger"></span>
                </div>

            <br>

            <div class="form-group">
                <a asp-action="Index" asp-route-id="@ViewBag.parentId"><button type="button" class="btn btn-secondary">@Localizer["Return"]</button></a>
                <input type="submit" value="@Localizer["Update"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</div>

Views/Folders/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using DMS.Models;
@inject IViewLocalizer Localizer;

@model dynamic

@{
    ViewBag.title = Localizer["FoldIndex"];
}

<h4>@Localizer["FoldIndex"]</h4>

<div class="rounded-10 p-2 div-br-color h-100">
<br>

<form asp-controller="Folders" asp-action="Index" method="get">
    <p>
        <a asp-action="Index" asp-route-id="@ViewBag.parentId"><i class="fas fa-arrow-left fa-lg"></i></a>
        <a asp-action="Create" asp-route-id="@ViewBag.currentID"><button type="button" class="btn btn-success">@Localizer["New Folder"]</button></a>
        <a asp-controller="Documents" asp-action="Create" asp-route-parentId="@ViewBag.currentID"><button type="button" class="btn btn-success">@Localizer["New Document"]</button></a>
        <input type="text" class="form-text" style="padding: 0.25rem; font-size: 1rem; font-weight: 400; line-height: 1.5; color: #212529; background-color: #fff; background-clip: padding-box; border: 1px solid #ced4da; border-radius: 0.25rem;" name="SearchString" value="@ViewBag.searchString"/>
        <input type="submit" class="btn btn-primary" value="@Localizer["Search"]"/>
    </p>
</form>


  <table class="table sortable">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                @Localizer[Html.DisplayNameForInnerType(((Document document) => document.Name))]
            </th>
            <th>
                @Localizer[Html.DisplayNameForInnerType(((Document document) => document.DateCreated))]
            </th>
            <th>
                @Localizer[Html.DisplayNameForInnerType(((Document document) => document.DateModified))]
            </th>
            <th>
                @Localizer[Html.DisplayNameForInnerType(((Document document) => document.Size))]
            </th>
            <th>
                @Localizer[Html.DisplayNameForInnerType(((Document document) => document.Extension))]
            </th>
            <th>@Localizer["Actions"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Folder folder in Model.Folders) {
            <tr>
                <td>
                    <i class="fas fa-folder fa-lg" style="color:Khaki"></i>
                </td>
                <td>
                    <a asp-action="index" asp-route-id="@folder.Id" style="text-decoration: none;">@Html.DisplayFor(folderItem => folder.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(folderItem => folder.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(folderItem => folder.DateModified)
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@folder.Id"><i class="fas fa-edit fa-lg" style="color:orange"></i></a> 
                    <a asp-action="Delete" asp-route-id="@folder.Id"><i class="fas fa-trash fa-lg" style="color:red"></i></a>
                </td>
            </tr>
        }
        @foreach (Document document in Model.Documents)
        {
            <tr>
                <td>
                    <i class="fas fa-file fa-lg" style="color:grey"></i> 
                </td>
                <td>
                    <a asp-controller="Documents" asp-action="Details" asp-route-id="@document.Id" style="text-decoration: none;">@Html.DisplayFor(documentItem => document.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(documentItem => document.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(documentItem => document.DateModified)
                </td>
                <td>
                    @Html.DisplayFor(documentItem => document.Size)
                </td>
                <td>
                    @Html.DisplayFor(documentItem => document.Extension)
                </td>
                <td> 
                    <a asp-controller="Documents" asp-action="Edit" asp-route-id="@document.Id"><i class="fas fa-edit fa-lg" style="color:orange"></i></a>
                    <a asp-controller="Documents" asp-action="Delete" asp-route-id="@document.Id"><i class="fas fa-trash fa-lg" style="color:red"></i></a>
                    <a asp-controller="Documents" asp-action="Download" asp-route-id="@document.Id"><i class="fas fa-download fa-lg" style="color:green"></i></a>
                    <a asp-controller="Documents" asp-action="Details" asp-route-id="@document.Id"><i class="fas fa-info-circle fa-lg"></i></a> 
                </td>
            </tr>
        }
    </tbody>
</table>

</div>
